apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: sliit-ctse
  name: sliit-ctse
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sliit-ctse
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sliit-ctse
    spec:
      containers:
      - image: shanukap/sliit-demo:c70a215be6ca98d5e110e63ef051786eaa9e7256
        imagePullPolicy: Always
        name: sliit-demo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 3005
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
