apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: ctse
  name: ctse
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ctse
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ctse
    spec:
      containers:
      - image: shanukap/sliit-demo:f296897d4ca7befed4752a647bf26bc57a08419e
        imagePullPolicy: Always
        name: sliit-demo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 3005
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
