apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: ctse-kube-app
  name: ctse-kube-app
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ctse-kube-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ctse-kube-app
    spec:
      containers:
      - image: shanukap/sliit-demo:700592b5b971f13cd19a701faea011c71d0499ac
        imagePullPolicy: Always
        name: sliit-demo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 3005
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30