apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse-kube-app
  name: ctse-kube-app
spec:
  ports:
  - port: 3005
    protocol: TCP
    targetPort: 3005
  selector:
    app: ctse-kube-app
status:
  loadBalancer: {}